version: '2'
services:
  php:
    build: ./docker_image
    entrypoint:
      - /bin/sh
      - -c
      - "([ -e 'vendor/autoload.php' ] || /entrypoint.sh composer update) && /entrypoint.sh run"
    ports:
      - "8888:80"
    volumes:
      - "./:/data"
    environment:
      WWW_DIR: "/data/web"
